# Generated by Django 3.2.10 on 2021-12-10 08:25

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('category_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=225)),
                ('ing_amount', models.IntegerField()),
                ('ing_units', models.CharField(max_length=225)),
                ('ing_description', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'Ingredients_data',
            },
        ),
        migrations.CreateModel(
            name='IngredientImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_image', models.ImageField(blank=True, upload_to='ingredientimages')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('caseQuantity', models.IntegerField()),
                ('packSize', models.IntegerField()),
                ('qtyUnits', models.CharField(choices=[('-- Weight --', (('Ounce (oz) (28.35 g)', 'Ounce (oz) (28.35 g)'), ('Pound (lb) (453.59 g)', 'Pound (lb) (453.59 g)'), ('Kilogram (Kg) (1000 g)', 'Kilogram (Kg) (1000 g)'), ('Tonne (T) (1000000 g)', 'Tonne (T) (1000000 g)'), ('Gram (g)', 'Gram (g)'))), ('-- Volume --', (('Pinch (pinch) (0.3 ml)', 'Pinch (pinch) (0.3 ml)'), ('US Teaspoon (tsp) (4.93 ml)', 'US Teaspoon (tsp) (4.93 ml)'), ('US Tablespoon (tbsp) (14.79 ml)', 'US Tablespoon (tbsp) (14.79 ml)'), ('Fluid-ounce (floz) (29.57 ml)', 'Fluid-ounce (floz) (29.57 ml)'), ('Deciliter (dL) (100 ml)', 'Deciliter (dL) (100 ml)'), ('US Cup (cup) (236.59 ml)', 'US Cup (cup) (236.59 ml)'), ('Pint (pt) (473.18 ml)', 'Pint (pt) (473.18 ml)'), ('Milliliter (ml)', 'Milliliter (ml)'), ('Quart (qt) (946.35 ml)', 'Quart (qt) (946.35 ml)'), ('Liter (L) (1000 ml)', 'Liter (L) (1000 ml)'), ('Gallon (gal) (3785.41 ml)', 'Gallon (gal) (3785.41 ml)'), ('Cubic Meter (kl) (1000000 ml)', 'Cubic Meter (kl) (1000000 ml)'), ('Each (each)', 'Each (each)'))), ('-- Quantity --', (('Dozen (dozen) (12 each)', 'Dozen (dozen) (12 each)'), ('Hundred (hundred) (100 each)', 'Hundred (hundred) (100 each)'), ('Thousand (thousand) (1000 each)', 'Thousand (thousand) (1000 each)'), ('Million (million) (1000000 each)', 'Million (million) (1000000 each)'))), ('-- Time --', (('Second (s)', 'Second (s)'), ('Minute (min) (60 s)', 'Minute (min) (60 s)'), ('Hour (hr) (3600 s)', 'Hour (hr) (3600 s)')))], max_length=225)),
                ('category', models.CharField(blank=True, max_length=225, null=True)),
                ('suppliers', models.CharField(blank=True, max_length=225, null=True)),
                ('orderCode', models.CharField(blank=True, max_length=225, null=True)),
                ('brand', models.CharField(blank=True, max_length=225, null=True)),
                ('countryOfOrigin', models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Canada', 'Canada'), ('United States', 'United States'), ('Aland Islands', 'Aland Islands'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Austria', 'Austria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('American Samoa', 'American Samoa'), ('Australia', 'Australia'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Barbados', 'Barbados'), ('Bangladesh', 'Bangladesh'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Bouvet Island', 'Bouvet Island'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'), ('Cayman Islands', 'Cayman Islands'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas Island', 'Christmas Island'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Cook Islands', 'Cook Islands'), ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Costa Rica', 'Costa Rica'), ('Curaçao', 'Curaçao'), ('Cyprus', 'Cyprus'), ('Denmark', 'Denmark'), ('Czech Republic', 'Czech Republic'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('Finland', 'Finland'), ('France', 'France'), ('French Guiana', 'French Guiana'), ('French Polynesia', 'French Polynesia'), ('Gabon', 'Gabon'), ('French Southern Territories', 'French Southern Territories'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Kuwait', 'Kuwait'), ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"), ('Kyrgyzstan', 'Kyrgyzstan'), ('Korea, Republic of', 'Korea, Republic of'), ('Latvia', 'Latvia'), ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao', 'Macao'), ('Malawi', 'Malawi'), ('Macedonia, Republic of', 'Macedonia, Republic of'), ('Madagascar', 'Madagascar'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mexico', 'Mexico'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Montserrat', 'Montserrat'), ('Micronesia, Federated States of', 'Micronesia, Federated States of'), ('Morocco', 'Morocco'), ('Myanmar', 'Myanmar'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Norfolk Island', 'Norfolk Island'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'), ('Palestine, State of', 'Palestine, State of'), ('Papua New Guinea', 'Papua New Guinea'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Philippines', 'Philippines'), ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Samoa', 'Samoa'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Saint Lucia', 'Saint Lucia'), ('Saint Barthélemy', 'Saint Barthélemy'), ('San Marino', 'San Marino'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saint Martin (French part)', 'Saint Martin (French part)'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Slovenia', 'Slovenia'), ('South Africa', 'South Africa'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Somalia', 'Somalia'), ('Solomon Islands', 'Solomon Islands'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Togo', 'Togo'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'United Kingdom'), ('United Arab Emirates', 'United Arab Emirates'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Viet Nam', 'Viet Nam'), ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Western Sahara', 'Western Sahara'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=225, null=True)),
                ('storageAreas', models.CharField(blank=True, max_length=225, null=True)),
                ('parLevel', models.IntegerField(blank=True, null=True)),
                ('parUnits', models.CharField(blank=True, choices=[('-- Weight --', (('Ounce (oz) (28.35 g)', 'Ounce (oz) (28.35 g)'), ('Pound (lb) (453.59 g)', 'Pound (lb) (453.59 g)'), ('Kilogram (Kg) (1000 g)', 'Kilogram (Kg) (1000 g)'), ('Tonne (T) (1000000 g)', 'Tonne (T) (1000000 g)'), ('Gram (g)', 'Gram (g)'))), ('-- Volume --', (('Pinch (pinch) (0.3 ml)', 'Pinch (pinch) (0.3 ml)'), ('US Teaspoon (tsp) (4.93 ml)', 'US Teaspoon (tsp) (4.93 ml)'), ('US Tablespoon (tbsp) (14.79 ml)', 'US Tablespoon (tbsp) (14.79 ml)'), ('Fluid-ounce (floz) (29.57 ml)', 'Fluid-ounce (floz) (29.57 ml)'), ('Deciliter (dL) (100 ml)', 'Deciliter (dL) (100 ml)'), ('US Cup (cup) (236.59 ml)', 'US Cup (cup) (236.59 ml)'), ('Pint (pt) (473.18 ml)', 'Pint (pt) (473.18 ml)'), ('Milliliter (ml)', 'Milliliter (ml)'), ('Quart (qt) (946.35 ml)', 'Quart (qt) (946.35 ml)'), ('Liter (L) (1000 ml)', 'Liter (L) (1000 ml)'), ('Gallon (gal) (3785.41 ml)', 'Gallon (gal) (3785.41 ml)'), ('Cubic Meter (kl) (1000000 ml)', 'Cubic Meter (kl) (1000000 ml)'), ('Each (each)', 'Each (each)'))), ('-- Quantity --', (('Dozen (dozen) (12 each)', 'Dozen (dozen) (12 each)'), ('Hundred (hundred) (100 each)', 'Hundred (hundred) (100 each)'), ('Thousand (thousand) (1000 each)', 'Thousand (thousand) (1000 each)'), ('Million (million) (1000000 each)', 'Million (million) (1000000 each)'))), ('-- Time --', (('Second (s)', 'Second (s)'), ('Minute (min) (60 s)', 'Minute (min) (60 s)'), ('Hour (hr) (3600 s)', 'Hour (hr) (3600 s)')))], max_length=225, null=True)),
                ('nutriationData', models.CharField(blank=True, max_length=225, null=True)),
                ('fdcId', models.CharField(blank=True, max_length=225, null=True)),
                ('fromMeasurementData', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('fromMeasurementUnits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('toMeasurementData', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('toMeasurementUnits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('hasMajorAllergens', models.BooleanField(blank=True, null=True)),
                ('majorAllergens', models.CharField(blank=True, max_length=225, null=True)),
                ('sugarAdded', models.BooleanField(blank=True, null=True)),
                ('usablePercentage', models.IntegerField(blank=True, null=True)),
                ('displayUnits', models.CharField(blank=True, max_length=225, null=True)),
                ('displayName', models.CharField(blank=True, max_length=225, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingredient_images', models.ManyToManyField(blank=True, to='recipesandingredients.IngredientImages')),
            ],
            options={
                'db_table': 'Ingredients_Table',
            },
        ),
        migrations.CreateModel(
            name='NutritionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('ingredient', models.CharField(max_length=225)),
                ('weight', models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='exmaple of valid weight be 240g or 240kg or 240lb', regex='\\d{1,9}(kg|lb)')])),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('total_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('saturated_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('trans_fat', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('sodium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('total_carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('dietary_fiber', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('sugar', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('protein', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_a', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_c', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('calcium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('iron', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('vitamin_d', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
                ('potassium', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Must be greater than or equal to 0')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('production_plan_template', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_image', models.ImageField(blank=True, upload_to='recipeimages')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=225)),
                ('target_yield', models.IntegerField()),
                ('category_batch', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('supplier_name', models.CharField(max_length=225)),
                ('order_email', models.EmailField(blank=True, max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('sales_rep_first_name', models.CharField(blank=True, max_length=225)),
                ('sales_rep_last_name', models.CharField(blank=True, max_length=225)),
                ('sales_rep_email', models.EmailField(blank=True, max_length=225)),
                ('sales_rep_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('preferred_order_method', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Text', 'Text'), ('Online Portal', 'Online Portal'), ('Fax', 'Fax')], max_length=225)),
                ('delivery_days', models.CharField(blank=True, max_length=225)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('recipe_user', models.CharField(max_length=225)),
                ('recipe_name', models.CharField(max_length=225)),
                ('recipe_category', models.CharField(blank=True, max_length=225, null=True)),
                ('recipe_yield_count', models.IntegerField()),
                ('yield_units', models.CharField(max_length=225)),
                ('preparation_instructions', django_quill.fields.QuillField(blank=True)),
                ('other_ing_data', models.ManyToManyField(to='recipesandingredients.IngredientData')),
                ('recipe_images', models.ManyToManyField(blank=True, to='recipesandingredients.RecipeImages')),
            ],
            options={
                'db_table': 'recipe_table',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('date_field', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', django_quill.fields.QuillField(blank=True)),
                ('recipes', models.ManyToManyField(blank=True, to='recipesandingredients.Recipes')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('caseQuantity', models.IntegerField()),
                ('packSize', models.IntegerField()),
                ('qtyUnits', models.CharField(choices=[('-- Weight --', (('Ounce (oz) (28.35 g)', 'Ounce (oz) (28.35 g)'), ('Pound (lb) (453.59 g)', 'Pound (lb) (453.59 g)'), ('Kilogram (Kg) (1000 g)', 'Kilogram (Kg) (1000 g)'), ('Tonne (T) (1000000 g)', 'Tonne (T) (1000000 g)'), ('Gram (g)', 'Gram (g)'))), ('-- Volume --', (('Pinch (pinch) (0.3 ml)', 'Pinch (pinch) (0.3 ml)'), ('US Teaspoon (tsp) (4.93 ml)', 'US Teaspoon (tsp) (4.93 ml)'), ('US Tablespoon (tbsp) (14.79 ml)', 'US Tablespoon (tbsp) (14.79 ml)'), ('Fluid-ounce (floz) (29.57 ml)', 'Fluid-ounce (floz) (29.57 ml)'), ('Deciliter (dL) (100 ml)', 'Deciliter (dL) (100 ml)'), ('US Cup (cup) (236.59 ml)', 'US Cup (cup) (236.59 ml)'), ('Pint (pt) (473.18 ml)', 'Pint (pt) (473.18 ml)'), ('Milliliter (ml)', 'Milliliter (ml)'), ('Quart (qt) (946.35 ml)', 'Quart (qt) (946.35 ml)'), ('Liter (L) (1000 ml)', 'Liter (L) (1000 ml)'), ('Gallon (gal) (3785.41 ml)', 'Gallon (gal) (3785.41 ml)'), ('Cubic Meter (kl) (1000000 ml)', 'Cubic Meter (kl) (1000000 ml)'), ('Each (each)', 'Each (each)'))), ('-- Quantity --', (('Dozen (dozen) (12 each)', 'Dozen (dozen) (12 each)'), ('Hundred (hundred) (100 each)', 'Hundred (hundred) (100 each)'), ('Thousand (thousand) (1000 each)', 'Thousand (thousand) (1000 each)'), ('Million (million) (1000000 each)', 'Million (million) (1000000 each)'))), ('-- Time --', (('Second (s)', 'Second (s)'), ('Minute (min) (60 s)', 'Minute (min) (60 s)'), ('Hour (hr) (3600 s)', 'Hour (hr) (3600 s)')))], max_length=225)),
                ('order_code', models.CharField(blank=True, max_length=225, null=True)),
                ('brand', models.CharField(blank=True, max_length=225, null=True)),
                ('country_of_origin', models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Canada', 'Canada'), ('United States', 'United States'), ('Aland Islands', 'Aland Islands'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Austria', 'Austria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('American Samoa', 'American Samoa'), ('Australia', 'Australia'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Barbados', 'Barbados'), ('Bangladesh', 'Bangladesh'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Bouvet Island', 'Bouvet Island'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'), ('Cayman Islands', 'Cayman Islands'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas Island', 'Christmas Island'), ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Cook Islands', 'Cook Islands'), ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Costa Rica', 'Costa Rica'), ('Curaçao', 'Curaçao'), ('Cyprus', 'Cyprus'), ('Denmark', 'Denmark'), ('Czech Republic', 'Czech Republic'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('Finland', 'Finland'), ('France', 'France'), ('French Guiana', 'French Guiana'), ('French Polynesia', 'French Polynesia'), ('Gabon', 'Gabon'), ('French Southern Territories', 'French Southern Territories'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Kuwait', 'Kuwait'), ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"), ('Kyrgyzstan', 'Kyrgyzstan'), ('Korea, Republic of', 'Korea, Republic of'), ('Latvia', 'Latvia'), ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao', 'Macao'), ('Malawi', 'Malawi'), ('Macedonia, Republic of', 'Macedonia, Republic of'), ('Madagascar', 'Madagascar'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mexico', 'Mexico'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Montserrat', 'Montserrat'), ('Micronesia, Federated States of', 'Micronesia, Federated States of'), ('Morocco', 'Morocco'), ('Myanmar', 'Myanmar'), ('Moldova, Republic of', 'Moldova, Republic of'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Norfolk Island', 'Norfolk Island'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'), ('Palestine, State of', 'Palestine, State of'), ('Papua New Guinea', 'Papua New Guinea'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Philippines', 'Philippines'), ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Samoa', 'Samoa'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('Saint Lucia', 'Saint Lucia'), ('Saint Barthélemy', 'Saint Barthélemy'), ('San Marino', 'San Marino'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saint Martin (French part)', 'Saint Martin (French part)'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Slovenia', 'Slovenia'), ('South Africa', 'South Africa'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Somalia', 'Somalia'), ('Solomon Islands', 'Solomon Islands'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Togo', 'Togo'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'United Kingdom'), ('United Arab Emirates', 'United Arab Emirates'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Viet Nam', 'Viet Nam'), ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Western Sahara', 'Western Sahara'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=225, null=True)),
                ('preferred', models.BooleanField(default=False)),
                ('ingredient_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesandingredients.ingredients')),
            ],
        ),
    ]
