subscription_plans = [
  {
  "title": "Limited",
  "price": 0,
  "description": "30 Day FREE trial. No credit card required",
  "purchase_link": "",
  "ingredients": 25,
  "recipes": 10,
  "sub_recipes": True,
  "margin_and_selling_calculator": True,
  "food_allergens": True,
  "ingredient_swapping": True,
  "supplier_management": True,
  "customer_management": True,
  "waste_and_Loss_calculator": True,
  "measurement_converter": True,
  "inventory_management": True,
  "ingredient_cost_history": True,
  "currency_preference": True,
  "recipe_scaling": True,
  "recipe_instructions": True,
  "image_uploading": True,
  "export_xls_csv": True,
  "print_save_pdf": True,
  "production_planning": True,
  "nutrition_data_and_labels": False,
},
  {
  "title": "Basic",
  "price": 14,
  "description": "$10/month if billed annually",
  "purchase_link": "",
  "ingredients": 'Unlimited',
  "recipes": 'Unlimited',
  "sub_recipes": True,
  "margin_and_selling_calculator": True,
  "food_allergens": True,
  "ingredient_swapping": True,
  "supplier_management": True,
  "customer_management": True,
  "waste_and_Loss_calculator": True,
  "measurement_converter": True,
  "inventory_management": True,
  "ingredient_cost_history": True,
  "currency_preference": True,
  "recipe_scaling": True,
  "recipe_instructions": True,
  "image_uploading": True,
  "export_xls_csv": True,
  "print_save_pdf": False,
  "production_planning": False,
  "nutrition_data_and_labels": False,
},
  {
  "title": "Standard",
  "price": 22,
  "description": "$18/month if billed annually",
  "purchase_link": "",
  "ingredients": 'Unlimited',
  "recipes": 'Unlimited',
  "sub_recipes": True,
  "margin_and_selling_calculator": True,
  "food_allergens": True,
  "ingredient_swapping": True,
  "supplier_management": True,
  "customer_management": True,
  "waste_and_Loss_calculator": True,
  "measurement_converter": True,
  "inventory_management": True,
  "ingredient_cost_history": True,
  "currency_preference": True,
  "recipe_scaling": True,
  "recipe_instructions": True,
  "image_uploading": True,
  "export_xls_csv": True,
  "print_save_pdf": True,
  "production_planning": True,
  "nutrition_data_and_labels": False,
},
  {
  "title": "Premium",
  "price": 29,
  "description": "24/month if billed annually",
  "purchase_link": "",
  "ingredients": 'Unlimited',
  "recipes": 'Unlimited',
  "sub_recipes": True,
  "margin_and_selling_calculator": True,
  "food_allergens": True,
  "ingredient_swapping": True,
  "supplier_management": True,
  "customer_management": True,
  "waste_and_Loss_calculator": True,
  "measurement_converter": True,
  "inventory_management": True,
  "ingredient_cost_history": True,
  "currency_preference": True,
  "recipe_scaling": True,
  "recipe_instructions": True,
  "image_uploading": True,
  "export_xls_csv": True,
  "print_save_pdf": True,
  "production_planning": True,
  "nutrition_data_and_labels": True,
},
]