# Generated by Django 3.2.10 on 2021-12-10 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('billing_email', models.EmailField(max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_one', models.CharField(blank=True, max_length=225)),
                ('address_two', models.CharField(blank=True, max_length=225)),
                ('city', models.CharField(blank=True, max_length=225)),
                ('country', models.CharField(blank=True, max_length=225)),
                ('postal_code', models.CharField(blank=True, max_length=225)),
                ('preferred_units', models.CharField(blank=True, choices=[('metric', 'metric'), ('imperial', 'imperial')], max_length=225)),
                ('use_advanced_cal', models.BooleanField(blank=True, default=False)),
                ('billing_country', models.CharField(blank=True, max_length=225)),
                ('currency_codes', models.CharField(blank=True, max_length=225)),
                ('round_currency', models.CharField(blank=True, max_length=225)),
                ('display_currency', models.CharField(blank=True, max_length=225)),
                ('own_currency', models.CharField(blank=True, max_length=225)),
                ('decimal_mark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(5, message='accept length of 5')])),
                ('thousands_separator', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(5, message='accept length of 5')])),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('contact_first_name', models.CharField(blank=True, max_length=225)),
                ('contact_last_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCarriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('contact_first_name', models.CharField(blank=True, max_length=225)),
                ('contact_last_name', models.CharField(blank=True, max_length=225)),
                ('email', models.EmailField(blank=True, max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
